Metamask_Home = "chrome-extension://iahmedeapmodoedininhafpahbolpnoi/home.html"
Metamask_Settings_Advance = f"{Metamask_Home}#settings/advanced"
Scroll_Alpha = "https://scroll.io/alpha"
Scroll_Bridge = "https://scroll.io/alpha/bridge"
Uniswap_Swap = "https://uniswap-v3.scroll.io/#/swap"
Uniswap_Swap_Usdc = "https://uniswap-v3.scroll.io/#/swap?outputCurrency=0xA0D71B9877f44C744546D649147E3F1e70a93760"
Remix = "https://remix.ethereum.org/"
