Metamask_Home = "chrome-extension://iahmedeapmodoedininhafpahbolpnoi/home.html"
Metamask_Settings_Advance = f"{Metamask_Home}#settings/advanced"
Scroll_Alpha = "https://scroll.io/alpha"
Scroll_Bridge = "https://scroll.io/alpha/bridge"
Uniswap_Swap = "https://uniswap-v3.scroll.io/#/swap"
